language: generic
install: .ci/install-crystax.sh
script:
  - ./build.sh ./crystax-ndk python3.7 3.7 v3.7.1
  - ./build.sh ./crystax-ndk python3.6 3.6 v3.6.7
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: crystax-ndk/sources/python
  on:
    branch: master
